import keymirror from 'keymirror'

export default keymirror({
  DEVICE_REGISTERED: null,
  DEVICE_REGISTERED_FAILED: null,
  DEVICE_UNREGISTERED: null,
  DEVICE_UNREGISTERED_FAILED: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILED: null,
  PROFILE_SUCCESS: null,
  PROFILE_FAILED: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILED: null,
  CREATE_ACCOUNT_SUCCESS: null,
  CREATE_ACCOUNT_FAILED: null,
  SESSION_TOKEN_SUCCESS: null,
  SESSION_TOKEN_FAILURE: null,
  ACTIVATION_SUCCESSFUL: null,
  ACTIVATION_FAILED: null,
  COMPLETE_RESET: null,
  LOGOUT: null
})
