import keymirror from "keymirror"

export default keymirror({
  DELETE_ANNOUNCEMENT: null,
  MARK_ANNOUNCEMENT_READ_STATUS: null,
  RECEIVE_ANNOUNCEMENTS_BEGIN: null,
  RECEIVE_ANNOUNCEMENTS_FAILED: null,
  RECEIVE_ANNOUNCEMENTS_SUCCESSFUL: null,
  RECEIVE_ASSIGNMENT_BEGIN: null,
  RECEIVE_ASSIGNMENT_FAILED: null,
  RECEIVE_ASSIGNMENT_SUCCESSFUL: null,
  RECEIVE_COURSE_BEGIN: null,
  RECEIVE_COURSE_FAILED: null,
  RECEIVE_COURSE_SUCCESSFUL: null,
  RECEIVE_COURSES_BEGIN: null,
  RECEIVE_COURSES_SUCCESSFUL: null,
  SELECT_ANNOUNCEMENT: null,
  SELECT_ASSIGNMENT: null,
  SELECT_COURSE: null,
  SELECT_COURSE_BY_ID: null,
})
