import keymirror from 'keymirror'

export default keymirror({
  DELETE_INTEGRATION: null,
  DELETE_INTEGRATION_FAILED: null,
  RECEIVE_INTEGRATION_STATUS: null,
  RECEIVE_INTEGRATION_STATUS_FAILED: null,
  UPDATE_INTEGRATION_NOTIFICATION_PERMISSION: null,
  UPDATE_INTEGRATION_NOTIFICATION_PERMISSION_FAILED: null
})
